### ISSUE TITLE
Issue when i ran php silver g controller news command

### ISSUE THREAD

**Issue by Techiejaat** [SilverEngine/Framework#22]
I received this notice when i ran php silver g controller news as per documents. Is this issue related to my php version.

PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/html/projects/silverEngine/System/Engine/CLI/index.php on line 227
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/html/projects/silverEngine/System/Engine/CLI/index.php on line 230
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/html/projects/silverEngine/System/Engine/CLI/index.php on line 230
PHP Warning:  file(/var/www/html/projects/silverEngine/AppDSRoutesDSWeb.php): failed to open stream: No such file or directory in /var/www/html/projects/silverEngine/System/Engine/CLI/index.php on line 232
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/projects/silverEngine/System/Engine/CLI/index.php on line 236
Route created!
controller news successfully created.

**Comment by SilverEngineTeam** [comment]
We will check it  please tell us more about wich version you downloaded
