### ISSUE TITLE
creating new controller : php silver g controller Logger

### ISSUE THREAD

**Issue by AntiGov** [SilverEngine/Framework#25]
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /root/Framework/System/Engine/CLI/index.php on line 227
PHP Stack trace:
PHP   1. {main}() /root/Framework/silver:0
PHP   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
PHP   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
PHP   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
PHP   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
PHP   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
PHP   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

Notice: Use of undefined constant DS - assumed 'DS' in /root/Framework/System/Engine/CLI/index.php on line 227

Call Stack:
    0.0002     357872   1. {main}() /root/Framework/silver:0
    0.0016     520488   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
    0.0016     520488   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
    0.0016     520488   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
    0.0017     520488   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
    0.0017     520648   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
    0.0142     523568   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

PHP Notice:  Use of undefined constant DS - assumed 'DS' in /root/Framework/System/Engine/CLI/index.php on line 230
PHP Stack trace:
PHP   1. {main}() /root/Framework/silver:0
PHP   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
PHP   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
PHP   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
PHP   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
PHP   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
PHP   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

Notice: Use of undefined constant DS - assumed 'DS' in /root/Framework/System/Engine/CLI/index.php on line 230

Call Stack:
    0.0002     357872   1. {main}() /root/Framework/silver:0
    0.0016     520488   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
    0.0016     520488   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
    0.0016     520488   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
    0.0017     520488   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
    0.0017     520648   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
    0.0142     523568   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

PHP Notice:  Use of undefined constant DS - assumed 'DS' in /root/Framework/System/Engine/CLI/index.php on line 230
PHP Stack trace:
PHP   1. {main}() /root/Framework/silver:0
PHP   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
PHP   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
PHP   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
PHP   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
PHP   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
PHP   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

Notice: Use of undefined constant DS - assumed 'DS' in /root/Framework/System/Engine/CLI/index.php on line 230

Call Stack:
    0.0002     357872   1. {main}() /root/Framework/silver:0
    0.0016     520488   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
    0.0016     520488   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
    0.0016     520488   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
    0.0017     520488   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
    0.0017     520648   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
    0.0142     523568   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

PHP Warning:  file(/root/Framework/AppDSRoutesDSWeb.php): failed to open stream: No such file or directory in /root/Framework/System/Engine/CLI/index.php on line 232
PHP Stack trace:
PHP   1. {main}() /root/Framework/silver:0
PHP   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
PHP   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
PHP   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
PHP   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
PHP   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
PHP   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196
PHP   8. file() /root/Framework/System/Engine/CLI/index.php:232

Warning: file(/root/Framework/AppDSRoutesDSWeb.php): failed to open stream: No such file or directory in /root/Framework/System/Engine/CLI/index.php on line 232

Call Stack:
    0.0002     357872   1. {main}() /root/Framework/silver:0
    0.0016     520488   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
    0.0016     520488   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
    0.0016     520488   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
    0.0017     520488   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
    0.0017     520648   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
    0.0142     523568   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196
    0.0145     523696   8. file() /root/Framework/System/Engine/CLI/index.php:232

PHP Warning:  Invalid argument supplied for foreach() in /root/Framework/System/Engine/CLI/index.php on line 236
PHP Stack trace:
PHP   1. {main}() /root/Framework/silver:0
PHP   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
PHP   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
PHP   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
PHP   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
PHP   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
PHP   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

Warning: Invalid argument supplied for foreach() in /root/Framework/System/Engine/CLI/index.php on line 236

Call Stack:
    0.0002     357872   1. {main}() /root/Framework/silver:0
    0.0016     520488   2. Silver\Engine\CLI->__construct() /root/Framework/silver:54
    0.0016     520488   3. Silver\Engine\CLI->run() /root/Framework/System/Engine/CLI/index.php:35
    0.0016     520488   4. Silver\Engine\CLI->make() /root/Framework/System/Engine/CLI/index.php:42
    0.0017     520488   5. Silver\Engine\CLI->generate() /root/Framework/System/Engine/CLI/index.php:96
    0.0017     520648   6. Silver\Engine\CLI->generateFile() /root/Framework/System/Engine/CLI/index.php:182
    0.0142     523568   7. Silver\Engine\CLI->fix_routes() /root/Framework/System/Engine/CLI/index.php:196

Route created!
controller Logger successfully created. (/root/Framework/App/Controllers/LoggerController.php)

**Comment by nmarulo** [comment]
my solution was:
- edit the "silver" file and add:

```php
define('DS', DIRECTORY_SEPARATOR);
include_once(ROOT.'System/Core/Env'.EXT);
```
-----

```php
#!/usr/bin/php
<?php

/**
 * SilverEngine  - PHP MVC framework
 *
 * @package   SilverEngine
 * @author    SilverEngine Team
 * @copyright 2015-2017
 * @license   MIT
 * @link      https://github.com/SilverEngine/Framework
 */

namespace Silver;

use Silver\Engine\CLI;

/**
 * Defining framework root directory
 * and jump into it.
 */
$CWD = str_replace('\\', '/', dirname(__FILE__));
$CWD = str_replace('/System/Engine/CLI', '', $CWD);
//ltrim($CWD);
define('ROOT', $CWD . '/');


/**
 * @param $data
 * @param bool $param
 */
if (!function_exists('dd')) {
    function dd($data, $param = false)
    {
        if ($param)
            var_dump('<pre>', $data, '<pre>');
        else
            var_dump($data);

        exit();
    }
}

/**
 * Defining php extension.
 */
define('EXT', '.php');
// directory separator to prevent conflict in different OS
define('DS', DIRECTORY_SEPARATOR);

include_once(ROOT.'System/Core/Blueprints/RenderInterface'.EXT);
include_once(ROOT.'System/Engine/Ghost/Template'.EXT);

include_once('System/Engine/CLI/index.php');
include_once(ROOT.'System/Core/Env'.EXT);

return new CLI($argv);

```
