### ISSUE TITLE
public/terminal route is not working.

### ISSUE THREAD

**Issue by mawaishanif** [SilverEngine/Framework#7]
There is a class name conflict with String keyword.
[First error start from here](https://github.com/SilverEngine/Framework/blob/master/System/App/Controllers/TerminalController.php#L22)
[See Class](https://github.com/SilverEngine/Framework/blob/master/System/Helpers/String.php#L15)

**Comment by SilverEngineTeam** [comment]
We will fix this problem  - it's deprecated CLI system

**Comment by SilverEngineTeam** [comment]
Will be in the next patch
